web_server_location = "australiaeast"
web_server_rg = "k8s"
resource_prefix = "web-server"
web_server_address_space = "10.0.0.0/22"
web_server_address_prefix = "10.0.1.0/24"
web_server_name = "web-01"
